myshop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myshop_app.urls')),
    path('', include('users_app.urls')),
]

myshop_app/urls.py
from django.urls import path
from . import views

app_name = 'myshop_app'

urlpatterns = [
    path('', views.AboutView.as_view(), name='about'),
    path('products/', views.ProductsView.as_view(), name='products'),
    path('products/<slug:slug>/', views.ProductView.as_view(), name='product'),
    path('add_product/', views.AddProduct.as_view(), name='add_product'),
    path('cart/', views.CartView.as_view(), name='cart'),
]

users_app/urls.py
from django.urls import path
from . import views

app_name = 'users_app'

urlpatterns = [
    path('login', views.UserLogin.as_view(), name='login'),
    path('logout', views.UserLogout.as_view(), name='logout'),
]

myshop_app/models.py
from django.urls import reverse
from django.db import models
from django.contrib.auth.models import User

class Product(models.Model):
    '''Product in the catalog'''
    title = models.CharField(max_length=50)
    specs = models.TextField(max_length=1000)
    image = models.CharField(max_length=50, unique=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    slug = models.SlugField(max_length=50, unique=True)

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('myshop_app:product', kwargs={'slug' : self.slug})

class Cart(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    product_id = models.ForeignKey(Product, on_delete=models.CASCADE)
    count = models.IntegerField(default=1)
    status = models.IntegerField(default=0)

    class Meta:
        verbose_name_plural = 'cart items'
        verbose_name = 'item'
    
    def __str__(self):
        return f'{self.user_id}:{self.product_id.title}:{self.count}:{self.status}'
    
    def add_count(self, count):
        self.count = count
        self.save()
        return
    
    def delete(self, using, keep_parents):
        return super().delete(using, keep_parents)
    
    def total(self):
        return self.product_id.price * self.count
    
    def grandtotal(cart_items):
        cart_grandtotal = 0
        for item in cart_items:
            cart_grandtotal += item.total()
        return cart_grandtotal

users_app/models.py
from django.db import models

# Create your models here.

myshop_app/forms.py
from django import forms
from .models import Product
from PIL import Image

PATH_IMG_ORIGINALS = 'myshop_app/static/myshop_app/img/originals/'
PATH_IMG_THUMBNAILS = 'myshop_app/static/myshop_app/img/thumbnails/'

class ProductForm(forms.ModelForm):

    file = forms.ImageField()

    class Meta():
        model = Product
        fields = ['title', 'specs', 'image', 'price']
    
    def save_image(self):
        with Image.open(self.cleaned_data['file']) as image:
            image.save(fp=f"{PATH_IMG_ORIGINALS}{self.cleaned_data['file']}")
            image.thumbnail((200, 200))
            image.save(fp=f"{PATH_IMG_THUMBNAILS}{self.cleaned_data['file']}")
    
    def clean(self):
        self.cleaned_data['image'] = self.cleaned_data['file']

myshop_app/views.py
from django.http.response import JsonResponse
from django.shortcuts import redirect
from django.urls import reverse_lazy
from .models import Product, Cart
from .forms import ProductForm
from django.views.generic.edit import CreateView
from django.views.generic import ListView, DetailView
from django.views.generic.base import TemplateView

class AboutView(TemplateView):
    template_name = 'about.html'

    def get_context_data(self, **kwargs):
        context = super(AboutView, self).get_context_data(**kwargs)
        context['page_title'] = 'About'
        return context

class ProductsView(ListView):
    model = Product
    template_name = 'products.html'
    context_object_name = 'products'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = 'Products'
        return context

class ProductView(DetailView):
    model = Product
    template_name = "product.html"
    context_object_name = 'product'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = self.object.title
        return context

class CartView(ListView):
    model = Cart
    template_name = "cart.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user_id = self.request.user.id
        cart_items = self.object_list.filter(user_id=user_id)
        grandtotal = self.model.grandtotal(cart_items)
        context['page_title'] = 'Cart'
        context['cart_items'] = cart_items
        context['grandtotal'] = grandtotal
        return context
    
    def post(self, request, *args, **kwargs):
        if request.POST.get('change_count'):
            cart_items = self.model.objects.all()
            cart_item = cart_items.get(id=request.POST.get('item_id'))
            cart_item.add_count(int(request.POST.get('change_count')))
            cart_items = cart_items.filter(user_id=self.request.user.id)
            response = {
                'grandtotal': self.model.grandtotal(cart_items),
                'total': cart_item.total(),
            }
            return JsonResponse(response)

class AddProduct(CreateView):
    form_class = ProductForm
    template_name = 'add_product.html'
    success_url = reverse_lazy('myshop_app:add_product')
    initial = {'image': 'filename'}

    def form_valid(self, form):
        form.clean()
        form.save_image()
        return super().form_valid(form)

    def get(self, request, *args, **kwargs):
        if not request.user.is_staff:
            return redirect('myshop_app:about')
        return super().get(request, *args, **kwargs)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = 'Add Product'
        return context

users_app/views.py
from django.contrib.auth.views import LoginView, LogoutView
from django.shortcuts import redirect

class UserLogin(LoginView):
    next_page = 'myshop_app:about'

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('myshop_app:about')
        return super().get(request, *args, **kwargs)
    
    def get_context_data(self, **kwargs):
        context = super(UserLogin, self).get_context_data(**kwargs)
        context['page_title'] = 'Login'
        return context

class UserLogout(LogoutView):
    extra_context = {'page_title': "Logout",}

    def get(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('myshop_app:about')
        return super().get(request, *args, **kwargs)

myshop_app/templates/myshop_app/about.html
{% extends 'myshop_app/base.html' %}
{% block content %}
<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum temporibus modi tempore facilis commodi dolore exercitationem, vero tempora ducimus, ipsam quae consectetur debitis! Numquam, architecto doloremque doloribus modi quo sunt.</p>
{% endblock content %}

myshop_app/templates/myshop_app/add_product.html
{% extends 'myshop_app/base.html' %}
{% block content %}
<form action="{% url 'myshop_app:add_product' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
        <h3>Add new product:</h3>
        <tr>
            <td>Title:</td>
            <td>{{ form.title }}</td>
        </tr>
        <tr>
            <td>Specs:</td>
            <td>{{ form.specs }}</td>
        </tr>
        <tr>
            <td>Price:</td>
            <td>{{ form.price }}</td>
        </tr>
        <tr>
            <td></td>
            <td>{{ form.image.as_hidden }}</td>
        </tr>
        <tr>
            <td>File:</td>
            <td>{{ form.file }}</td>
        </tr>
    </table>
    <button name='submit'>Add new product</button>
</form>
{% endblock content %}

myshop_app/templates/myshop_app/administrator.html
{% extends 'myshop_app/base.html' %}
{% block content %}
<form action="{% url 'myshop_app:administrator' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
        <h3>Add new product:</h3>
        <tr>
            <td>Title:</td>
            <td>{{ form.title }}</td>
        </tr>
        <tr>
            <td>Specs:</td>
            <td>{{ form.specs }}</td>
        </tr>
        <tr>
            <td>Price:</td>
            <td>{{ form.price }}</td>
        </tr>
        <tr>
            <td></td>
            <td>{{ form.image.as_hidden }}</td>
        </tr>
        <tr>
            <td>File:</td>
            <td>{{ form.file }}</td>
        </tr>
    </table>
    <button name='submit'>Add new product</button>
</form>
{% endblock content %}

myshop_app/templates/myshop_app/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link rel="shortcut icon" type="image/png" href="{% static 'myshop_app/favicon.ico' %}"/>
    <link rel="stylesheet" href="{% static 'myshop_app/css/stylesheet.css' %}">
    <title>{{ page_title }}</title>
</head>
<body>
    <header>
    {% include 'header_menu.html' %}
    </header>
    <h1>{{ page_title }}</h1>
    {% block content %}
    {% endblock content %}
</body>
</html>

myshop_app/templates/myshop_app/cart.html
{% extends 'myshop_app/base.html' %}
{% block content %}

{% if cart_items %}
<h3>Selected items:</h3>
<form method="post" id="cart-form">
{% csrf_token %}
<table class="cart-table">
<tr>
    <th class="cart-table-th">No.</th>
    <th class="cart-table-th">Product</th>
    <th class="cart-table-th">Qty.</th>
    <th class="cart-table-th">Price</th>
    <th class="cart-table-th">Total</th>
    <th class="cart-table-th">Delete</th>
</tr>
{% for item in cart_items %}
<tr>
    <td class="cart-table-td">{{ item.id }}.</td>
    <td class="cart-table-td"><a href="{% url 'myshop_app:products' %}{{item.product_id.id}}">{{ item.product_id }}</a></td>
    <td class="cart-table-td"><input name='change_count' type="number" min='1' max='100' value="{{ item.count }}" style="width: 3em" id="{{ item.id }}"></td>
    <td class="cart-table-td">{{ item.product_id.price }}</td>
    <td class="cart-table-td" id="output-total{{ item.id }}">{{ item.total }}</td>
    <td><input type="submit" name='del' id="{{ item.id }}" value="del"></td>    
</tr>
{% endfor %}
</table>
<p><strong>Grandtotal: </strong><span id="output-grandtotal">{{ grandtotal }}</span></p>
<button type="submit">Finish your order</button>
</form>
{% else %}
<h3>No items added here yet...</h3>
{% endif %}

<script>
    arr = document.getElementsByName('change_count');
    arr.forEach(cart_item => {
       $(`#${cart_item.id}`).on('change', function(e){
        e.preventDefault();
          $.ajax({
               type : "POST", 
               url: "{% url 'myshop_app:cart' %}",
               data: {
                change_count: cart_item.value,
                item_id: cart_item.id,
                csrfmiddlewaretoken: '{{ csrf_token }}',
                dataType: `json`,
               },
               success: function(data){
                $(`#output-total${cart_item.id}`).html(data.total); 
                $(`#output-grandtotal`).html(data.grandtotal);
               },
               failure: function() {
               }
           });
        });
    });     
 </script>
{% endblock content %}

myshop_app/templates/myshop_app/header_menu.html
{% load myshop_app_tags %}
{% get_header_menu as header_menu %}

<div class="menu-div">
    <ul>
    {% for item in header_menu %}
    {% url item.url as url_name %}
        {% if request.path == url_name %}
            <li class="menu-item-li menu-active">{{ item.title }}</li>
        {% else %}
            <li class="menu-item-li"><a class="menu-item-a" href="{{ url_name }}">{{ item.title }}</a></li>
        {% endif %}
    {% endfor %}
    </ul>
</div>

myshop_app/templates/myshop_app/product.html
{% extends 'myshop_app/base.html' %}

{% load static %}
{% block content %}
<div class="product-container">
    <a href="{% static 'myshop_app/img/originals/' %}{{ product.image }}"><img src="{% static 'myshop_app/img/thumbnails/' %}{{ product.image }}" height="200" width="200" alt="{{ product.image }}"></a>
    <p>{{ product.specs }}</p>
    <p>{{ product.price }} &#8381;</p>
    <input type="submit" value="Buy">
</div>
{% endblock content %}

myshop_app/templates/myshop_app/products.html
{% extends 'myshop_app/base.html' %}
{% load static %}

{% block content %}
<div class="products-container">
    {% for product in products %}
    <div class="product-container">
        <a href="{{ product.get_absolute_url }}"><h3>{{ product.title }}</h3></a>
        <a href="{{ product.get_absolute_url }}"><img src="{% static 'myshop_app/img/thumbnails/' %}{{ product.image }}" height="200" width="200" alt="{{ product.image }}"></a>
        <p>{{ product.price }} &#8381;</p>
        <input type="submit" value="Buy">
    </div>
    {% endfor %}
</div>
{% endblock content %}